//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehiclesServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colour
    {
        public Colour()
        {
            this.VehicleStockItems = new HashSet<VehicleStockItem>();
        }
    
        public int ColourID { get; set; }
        public string ColourName { get; set; }
        public bool Metallic { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<VehicleStockItem> VehicleStockItems { get; set; }
    }
}
