//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehiclesServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleStockItem
    {
        public int VehicleStockItemID { get; set; }
        public int ColourID { get; set; }
        public int VehicleTypeID { get; set; }
        public int WheelTypeID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Registration { get; set; }
        public decimal Price { get; set; }
        public int Capacity { get; set; }
        public bool Automatic { get; set; }
        public bool Sold { get; set; }
        public System.DateTime StockEntryDate { get; set; }
        public System.DateTime DateNew { get; set; }
        public string Notes { get; set; }
    
        public virtual Colour Colour { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual WheelType WheelType { get; set; }
    }
}
