//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehiclesServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType
    {
        public VehicleType()
        {
            this.VehicleStockItems = new HashSet<VehicleStockItem>();
        }
    
        public int VehicleTypeID { get; set; }
        public string VehicleTypeName { get; set; }
        public int NoDoors { get; set; }
        public int MaxSeats { get; set; }
    
        public virtual ICollection<VehicleStockItem> VehicleStockItems { get; set; }
    }
}
