//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehiclesServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WheelType
    {
        public WheelType()
        {
            this.VehicleStockItems = new HashSet<VehicleStockItem>();
        }
    
        public int WheelTypeID { get; set; }
        public string WheelTypeName { get; set; }
        public int Spokes { get; set; }
        public int Width { get; set; }
        public int Profile { get; set; }
        public int Diameter { get; set; }
        public bool Alloy { get; set; }
    
        public virtual ICollection<VehicleStockItem> VehicleStockItems { get; set; }
    }
}
