//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehiclesClient.VehicleReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleListing", Namespace="http://schemas.datacontract.org/2004/07/VehiclesServer")]
    [System.SerializableAttribute()]
    public partial class VehicleListing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WheelTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colour {
            get {
                return this.ColourField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourField, value) != true)) {
                    this.ColourField = value;
                    this.RaisePropertyChanged("Colour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make {
            get {
                return this.MakeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeField, value) != true)) {
                    this.MakeField = value;
                    this.RaisePropertyChanged("Make");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sold {
            get {
                return this.SoldField;
            }
            set {
                if ((this.SoldField.Equals(value) != true)) {
                    this.SoldField = value;
                    this.RaisePropertyChanged("Sold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleType {
            get {
                return this.VehicleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleTypeField, value) != true)) {
                    this.VehicleTypeField = value;
                    this.RaisePropertyChanged("VehicleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WheelType {
            get {
                return this.WheelTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.WheelTypeField, value) != true)) {
                    this.WheelTypeField = value;
                    this.RaisePropertyChanged("WheelType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.gcal.ac.uk", ConfigurationName="VehicleReference.IVehicleService")]
    public interface IVehicleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getStudentId", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getStudentIdResponse")]
        string getStudentId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getStudentId", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getStudentIdResponse")]
        System.Threading.Tasks.Task<string> getStudentIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getListingsCount", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getListingsCountResponse")]
        int getListingsCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getListingsCount", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getListingsCountResponse")]
        System.Threading.Tasks.Task<int> getListingsCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getAllListings", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getAllListingsResponse")]
        VehiclesClient.VehicleReference.VehicleListing[] getAllListings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getAllListings", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getAllListingsResponse")]
        System.Threading.Tasks.Task<VehiclesClient.VehicleReference.VehicleListing[]> getAllListingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getListingsByPriceRange", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getListingsByPriceRangeResponse")]
        VehiclesClient.VehicleReference.VehicleListing[] getListingsByPriceRange(int rangeLow, int rangeHigh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getListingsByPriceRange", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getListingsByPriceRangeResponse")]
        System.Threading.Tasks.Task<VehiclesClient.VehicleReference.VehicleListing[]> getListingsByPriceRangeAsync(int rangeLow, int rangeHigh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getListingsByColour", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getListingsByColourResponse")]
        VehiclesClient.VehicleReference.VehicleListing[] getListingsByColour(string colour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/getListingsByColour", ReplyAction="http://services.gcal.ac.uk/IVehicleService/getListingsByColourResponse")]
        System.Threading.Tasks.Task<VehiclesClient.VehicleReference.VehicleListing[]> getListingsByColourAsync(string colour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/toggleListingSold", ReplyAction="http://services.gcal.ac.uk/IVehicleService/toggleListingSoldResponse")]
        void toggleListingSold(int listingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/toggleListingSold", ReplyAction="http://services.gcal.ac.uk/IVehicleService/toggleListingSoldResponse")]
        System.Threading.Tasks.Task toggleListingSoldAsync(int listingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/deleteListing", ReplyAction="http://services.gcal.ac.uk/IVehicleService/deleteListingResponse")]
        void deleteListing(int listingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/deleteListing", ReplyAction="http://services.gcal.ac.uk/IVehicleService/deleteListingResponse")]
        System.Threading.Tasks.Task deleteListingAsync(int listingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/createListing", ReplyAction="http://services.gcal.ac.uk/IVehicleService/createListingResponse")]
        void createListing(System.Collections.Generic.Dictionary<string, string> args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gcal.ac.uk/IVehicleService/createListing", ReplyAction="http://services.gcal.ac.uk/IVehicleService/createListingResponse")]
        System.Threading.Tasks.Task createListingAsync(System.Collections.Generic.Dictionary<string, string> args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehicleServiceChannel : VehiclesClient.VehicleReference.IVehicleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleServiceClient : System.ServiceModel.ClientBase<VehiclesClient.VehicleReference.IVehicleService>, VehiclesClient.VehicleReference.IVehicleService {
        
        public VehicleServiceClient() {
        }
        
        public VehicleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getStudentId() {
            return base.Channel.getStudentId();
        }
        
        public System.Threading.Tasks.Task<string> getStudentIdAsync() {
            return base.Channel.getStudentIdAsync();
        }
        
        public int getListingsCount() {
            return base.Channel.getListingsCount();
        }
        
        public System.Threading.Tasks.Task<int> getListingsCountAsync() {
            return base.Channel.getListingsCountAsync();
        }
        
        public VehiclesClient.VehicleReference.VehicleListing[] getAllListings() {
            return base.Channel.getAllListings();
        }
        
        public System.Threading.Tasks.Task<VehiclesClient.VehicleReference.VehicleListing[]> getAllListingsAsync() {
            return base.Channel.getAllListingsAsync();
        }
        
        public VehiclesClient.VehicleReference.VehicleListing[] getListingsByPriceRange(int rangeLow, int rangeHigh) {
            return base.Channel.getListingsByPriceRange(rangeLow, rangeHigh);
        }
        
        public System.Threading.Tasks.Task<VehiclesClient.VehicleReference.VehicleListing[]> getListingsByPriceRangeAsync(int rangeLow, int rangeHigh) {
            return base.Channel.getListingsByPriceRangeAsync(rangeLow, rangeHigh);
        }
        
        public VehiclesClient.VehicleReference.VehicleListing[] getListingsByColour(string colour) {
            return base.Channel.getListingsByColour(colour);
        }
        
        public System.Threading.Tasks.Task<VehiclesClient.VehicleReference.VehicleListing[]> getListingsByColourAsync(string colour) {
            return base.Channel.getListingsByColourAsync(colour);
        }
        
        public void toggleListingSold(int listingId) {
            base.Channel.toggleListingSold(listingId);
        }
        
        public System.Threading.Tasks.Task toggleListingSoldAsync(int listingId) {
            return base.Channel.toggleListingSoldAsync(listingId);
        }
        
        public void deleteListing(int listingId) {
            base.Channel.deleteListing(listingId);
        }
        
        public System.Threading.Tasks.Task deleteListingAsync(int listingId) {
            return base.Channel.deleteListingAsync(listingId);
        }
        
        public void createListing(System.Collections.Generic.Dictionary<string, string> args) {
            base.Channel.createListing(args);
        }
        
        public System.Threading.Tasks.Task createListingAsync(System.Collections.Generic.Dictionary<string, string> args) {
            return base.Channel.createListingAsync(args);
        }
    }
}
